### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by davisjam** [uhop/node-re2#10]
I tried to clone and build. I'm using nvm.

```
(12:34:15) jamie@jamie-Lenovo-K450e /tmp $ git clone git@github.com:uhop/node-re2.git
Cloning into 'node-re2'...
remote: Counting objects: 582, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 582 (delta 0), reused 0 (delta 0), pack-reused 580
Receiving objects: 100% (582/582), 382.73 KiB | 0 bytes/s, done.
Resolving deltas: 100% (324/324), done.
Checking connectivity... done.
(12:34:18) jamie@jamie-Lenovo-K450e /tmp $ cd node-re2
(12:34:20) jamie@jamie-Lenovo-K450e /tmp/node-re2 $ npm install

> re2@1.4.1 install /tmp/node-re2
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/tmp/node-re2/build'
  CXX(target) Release/obj.target/re2/lib/addon.o
  CXX(target) Release/obj.target/re2/lib/new.o
  CXX(target) Release/obj.target/re2/lib/exec.o
  CXX(target) Release/obj.target/re2/lib/test.o
  CXX(target) Release/obj.target/re2/lib/match.o
  CXX(target) Release/obj.target/re2/lib/replace.o
  CXX(target) Release/obj.target/re2/lib/search.o
  CXX(target) Release/obj.target/re2/lib/split.o
  CXX(target) Release/obj.target/re2/lib/to_string.o
  CXX(target) Release/obj.target/re2/lib/accessors.o
  CXX(target) Release/obj.target/re2/lib/util.o
make: *** No rule to make target 'Release/obj.target/re2/vendor/re2/bitstate.o', needed by 'Release/obj.target/re2.node'.  Stop.
make: Leaving directory '/tmp/node-re2/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/jamie/.nvm/versions/node/v6.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.8.0-49-generic
gyp ERR! command "/home/jamie/.nvm/versions/node/v6.10.0/bin/node" "/home/jamie/.nvm/versions/node/v6.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/node-re2
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Linux 4.8.0-49-generic
npm ERR! argv "/home/jamie/.nvm/versions/node/v6.10.0/bin/node" "/home/jamie/.nvm/versions/node/v6.10.0/bin/npm" "install"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! re2@1.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the re2@1.4.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the re2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs re2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls re2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/node-re2/npm-debug.log
```

[npm-debug.log.txt](https://github.com/uhop/node-re2/files/987321/npm-debug.log.txt)

**Comment by uhop** [comment]
Thank you for reporting the bug. I'll try to repro it, and will fix it as soon as I can.

**Comment by uhop** [comment]
It fails on the very first `vendor` file meaning that `RE2`, which is included as a git submodule, is not there. For submodules, you can issue a command:

    git submodule update --init --recursive

Do it right after cloning.

I need to add it to the documentation.

**Comment by davisjam** [comment]
Great, with the updated docs it worked fine.
