### ISSUE TITLE
cannot install re2 in my node js service

### ISSUE THREAD

**Issue by bruno-massagli** [uhop/node-re2#46]
```
npm WARN package.json mathhack@1.0.0 No README.md file found!
npm WARN package.json copy-descriptor@0.1.1 No README.md file found!
npm WARN package.json estraverse@4.2.0 No README.md file found!
npm WARN package.json get-value@2.0.6 No README.md file found!
npm WARN package.json object-copy@0.1.0 No README.md file found!
npm WARN package.json path-is-inside@1.0.2 No README.md file found!
npm WARN package.json pstree.remy@1.1.0 No README.md file found!
npm WARN package.json static-extend@0.1.2 No README.md file found!
npm http GET https://registry.npmjs.org/re2
npm http GET https://registry.npmjs.org/re2
npm http GET https://registry.npmjs.org/re2
npm ERR! Error: unable to get local issuer certificate
npm ERR!     at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
npm ERR!     at emitNone (events.js:106:13)
npm ERR!     at TLSSocket.emit (events.js:208:7)
npm ERR!     at TLSSocket._finishInit (_tls_wrap.js:639:8)
npm ERR!     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "re2"
npm ERR! cwd C:\www\math
npm ERR! node -v v8.11.3
npm ERR! npm -v 1.1.48
npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\www\math\npm-debug.log
npm ERR! not ok code 0``
```

```
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   're2' ]
2 info using npm@1.1.48
3 info using node@v8.11.3
4 verbose config file C:\Users\user\.npmrc
5 verbose config file C:\Program Files\nodejs\etc\npmrc
6 verbose config file C:\Users\user\AppData\Roaming\nvm\v8.11.3\node_modules\npm\npmrc
7 verbose read json C:\www\math\package.json
8 warn package.json mathhack@1.0.0 No README.md file found!
9 verbose read json C:\www\math\node_modules\abbrev\package.json
10 verbose read json C:\www\math\node_modules\accepts\package.json
11 verbose read json C:\www\math\node_modules\acorn\package.json
12 verbose read json C:\www\math\node_modules\acorn-jsx\package.json
13 verbose read json C:\www\math\node_modules\ajv\package.json
14 verbose read json C:\www\math\node_modules\ajv-keywords\package.json
15 verbose read json C:\www\math\node_modules\ansi-align\package.json
16 verbose read json C:\www\math\node_modules\ansi-escapes\package.json
17 verbose read json C:\www\math\node_modules\ansi-regex\package.json
18 verbose read json C:\www\math\node_modules\ansi-styles\package.json
19 verbose read json C:\www\math\node_modules\anymatch\package.json
20 verbose read json C:\www\math\node_modules\argparse\package.json
21 verbose read json C:\www\math\node_modules\arr-diff\package.json
22 verbose read json C:\www\math\node_modules\arr-flatten\package.json
23 verbose read json C:\www\math\node_modules\arr-union\package.json
24 verbose read json C:\www\math\node_modules\array-flatten\package.json
25 verbose read json C:\www\math\node_modules\array-union\package.json
26 verbose read json C:\www\math\node_modules\array-uniq\package.json
27 verbose read json C:\www\math\node_modules\array-unique\package.json
28 verbose read json C:\www\math\node_modules\arrify\package.json
29 verbose read json C:\www\math\node_modules\assign-symbols\package.json
30 verbose read json C:\www\math\node_modules\async-each\package.json
31 verbose read json C:\www\math\node_modules\atob\package.json
32 verbose read json C:\www\math\node_modules\babel-code-frame\package.json
33 verbose read json C:\www\math\node_modules\balanced-match\package.json
34 verbose read json C:\www\math\node_modules\base\package.json
35 verbose read json C:\www\math\node_modules\binary-extensions\package.json
36 verbose read json C:\www\math\node_modules\body-parser\package.json
37 verbose read json C:\www\math\node_modules\boxen\package.json
38 verbose read json C:\www\math\node_modules\brace-expansion\package.json
39 verbose read json C:\www\math\node_modules\braces\package.json
40 verbose read json C:\www\math\node_modules\bytes\package.json
41 verbose read json C:\www\math\node_modules\cache-base\package.json
42 verbose read json C:\www\math\node_modules\caller-path\package.json
43 verbose read json C:\www\math\node_modules\callsites\package.json
44 verbose read json C:\www\math\node_modules\capture-stack-trace\package.json
45 verbose read json C:\www\math\node_modules\chalk\package.json
46 verbose read json C:\www\math\node_modules\chardet\package.json
47 verbose read json C:\www\math\node_modules\chokidar\package.json
48 verbose read json C:\www\math\node_modules\ci-info\package.json
49 verbose read json C:\www\math\node_modules\circular-json\package.json
50 verbose read json C:\www\math\node_modules\class-utils\package.json
51 verbose read json C:\www\math\node_modules\cli-boxes\package.json
52 verbose read json C:\www\math\node_modules\cli-cursor\package.json
53 verbose read json C:\www\math\node_modules\cli-width\package.json
54 verbose read json C:\www\math\node_modules\collection-visit\package.json
55 verbose read json C:\www\math\node_modules\color-convert\package.json
56 verbose read json C:\www\math\node_modules\color-name\package.json
57 verbose read json C:\www\math\node_modules\component-emitter\package.json
58 verbose read json C:\www\math\node_modules\concat-map\package.json
59 verbose read json C:\www\math\node_modules\configstore\package.json
60 verbose read json C:\www\math\node_modules\content-disposition\package.json
61 verbose read json C:\www\math\node_modules\content-type\package.json
62 verbose read json C:\www\math\node_modules\cookie\package.json
63 verbose read json C:\www\math\node_modules\cookie-signature\package.json
64 verbose read json C:\www\math\node_modules\copy-descriptor\package.json
65 verbose read json C:\www\math\node_modules\core-util-is\package.json
66 verbose read json C:\www\math\node_modules\create-error-class\package.json
67 verbose read json C:\www\math\node_modules\cross-spawn\package.json
68 verbose read json C:\www\math\node_modules\crypto-random-string\package.json
69 verbose read json C:\www\math\node_modules\debug\package.json
70 verbose read json C:\www\math\node_modules\decode-uri-component\package.json
71 verbose read json C:\www\math\node_modules\deep-extend\package.json
72 verbose read json C:\www\math\node_modules\deep-is\package.json
73 verbose read json C:\www\math\node_modules\define-properties\package.json
74 verbose read json C:\www\math\node_modules\define-property\package.json
75 verbose read json C:\www\math\node_modules\del\package.json
76 verbose read json C:\www\math\node_modules\depd\package.json
77 verbose read json C:\www\math\node_modules\destroy\package.json
78 verbose read json C:\www\math\node_modules\doctrine\package.json
79 verbose read json C:\www\math\node_modules\dot-prop\package.json
80 verbose read json C:\www\math\node_modules\duplexer\package.json
81 verbose read json C:\www\math\node_modules\duplexer3\package.json
82 verbose read json C:\www\math\node_modules\ee-first\package.json
83 verbose read json C:\www\math\node_modules\encodeurl\package.json
84 verbose read json C:\www\math\node_modules\es-abstract\package.json
85 verbose read json C:\www\math\node_modules\es-to-primitive\package.json
86 verbose read json C:\www\math\node_modules\escape-html\package.json
87 verbose read json C:\www\math\node_modules\escape-string-regexp\package.json
88 verbose read json C:\www\math\node_modules\eslint\package.json
89 verbose read json C:\www\math\node_modules\eslint-scope\package.json
90 verbose read json C:\www\math\node_modules\eslint-visitor-keys\package.json
91 verbose read json C:\www\math\node_modules\espree\package.json
92 verbose read json C:\www\math\node_modules\esprima\package.json
93 verbose read json C:\www\math\node_modules\esquery\package.json
94 verbose read json C:\www\math\node_modules\esrecurse\package.json
95 verbose read json C:\www\math\node_modules\estraverse\package.json
96 verbose read json C:\www\math\node_modules\esutils\package.json
97 verbose read json C:\www\math\node_modules\etag\package.json
98 verbose read json C:\www\math\node_modules\event-stream\package.json
99 verbose read json C:\www\math\node_modules\execa\package.json
100 verbose read json C:\www\math\node_modules\expand-brackets\package.json
101 verbose read json C:\www\math\node_modules\express\package.json
102 verbose read json C:\www\math\node_modules\extend-shallow\package.json
103 verbose read json C:\www\math\node_modules\external-editor\package.json
104 verbose read json C:\www\math\node_modules\extglob\package.json
105 verbose read json C:\www\math\node_modules\fast-deep-equal\package.json
106 verbose read json C:\www\math\node_modules\fast-json-stable-stringify\package.json
107 verbose read json C:\www\math\node_modules\fast-levenshtein\package.json
108 verbose read json C:\www\math\node_modules\figures\package.json
109 verbose read json C:\www\math\node_modules\file-entry-cache\package.json
110 verbose read json C:\www\math\node_modules\fill-range\package.json
111 verbose read json C:\www\math\node_modules\finalhandler\package.json
112 verbose read json C:\www\math\node_modules\flat-cache\package.json
113 verbose read json C:\www\math\node_modules\for-in\package.json
114 verbose read json C:\www\math\node_modules\foreach\package.json
115 verbose read json C:\www\math\node_modules\forwarded\package.json
116 verbose read json C:\www\math\node_modules\fragment-cache\package.json
117 verbose read json C:\www\math\node_modules\fresh\package.json
118 verbose read json C:\www\math\node_modules\from\package.json
119 verbose read json C:\www\math\node_modules\fs.realpath\package.json
120 verbose read json C:\www\math\node_modules\function-bind\package.json
121 verbose read json C:\www\math\node_modules\functional-red-black-tree\package.json
122 verbose read json C:\www\math\node_modules\get-stream\package.json
123 verbose read json C:\www\math\node_modules\get-value\package.json
124 verbose read json C:\www\math\node_modules\glob\package.json
125 verbose read json C:\www\math\node_modules\glob-parent\package.json
126 verbose read json C:\www\math\node_modules\global-dirs\package.json
127 verbose read json C:\www\math\node_modules\globals\package.json
128 verbose read json C:\www\math\node_modules\globby\package.json
129 verbose read json C:\www\math\node_modules\got\package.json
130 verbose read json C:\www\math\node_modules\graceful-fs\package.json
131 verbose read json C:\www\math\node_modules\has\package.json
132 verbose read json C:\www\math\node_modules\has-ansi\package.json
133 verbose read json C:\www\math\node_modules\has-flag\package.json
134 verbose read json C:\www\math\node_modules\has-symbols\package.json
135 verbose read json C:\www\math\node_modules\has-value\package.json
136 verbose read json C:\www\math\node_modules\has-values\package.json
137 verbose read json C:\www\math\node_modules\http-errors\package.json
138 verbose read json C:\www\math\node_modules\iconv-lite\package.json
139 verbose read json C:\www\math\node_modules\ignore\package.json
140 verbose read json C:\www\math\node_modules\ignore-by-default\package.json
141 verbose read json C:\www\math\node_modules\import-lazy\package.json
142 verbose read json C:\www\math\node_modules\imurmurhash\package.json
143 verbose read json C:\www\math\node_modules\inflight\package.json
144 verbose read json C:\www\math\node_modules\inherits\package.json
145 verbose read json C:\www\math\node_modules\ini\package.json
146 verbose read json C:\www\math\node_modules\inquirer\package.json
147 verbose read json C:\www\math\node_modules\ipaddr.js\package.json
148 verbose read json C:\www\math\node_modules\is-accessor-descriptor\package.json
149 verbose read json C:\www\math\node_modules\is-binary-path\package.json
150 verbose read json C:\www\math\node_modules\is-buffer\package.json
151 verbose read json C:\www\math\node_modules\is-callable\package.json
152 verbose read json C:\www\math\node_modules\is-ci\package.json
153 verbose read json C:\www\math\node_modules\is-data-descriptor\package.json
154 verbose read json C:\www\math\node_modules\is-date-object\package.json
155 verbose read json C:\www\math\node_modules\is-descriptor\package.json
156 verbose read json C:\www\math\node_modules\is-extendable\package.json
157 verbose read json C:\www\math\node_modules\is-extglob\package.json
158 verbose read json C:\www\math\node_modules\is-glob\package.json
159 verbose read json C:\www\math\node_modules\is-installed-globally\package.json
160 verbose read json C:\www\math\node_modules\is-npm\package.json
161 verbose read json C:\www\math\node_modules\is-number\package.json
162 verbose read json C:\www\math\node_modules\is-obj\package.json
163 verbose read json C:\www\math\node_modules\is-path-cwd\package.json
164 verbose read json C:\www\math\node_modules\is-path-in-cwd\package.json
165 verbose read json C:\www\math\node_modules\is-path-inside\package.json
166 verbose read json C:\www\math\node_modules\is-plain-object\package.json
167 verbose read json C:\www\math\node_modules\is-promise\package.json
168 verbose read json C:\www\math\node_modules\is-redirect\package.json
169 verbose read json C:\www\math\node_modules\is-regex\package.json
170 verbose read json C:\www\math\node_modules\is-resolvable\package.json
171 verbose read json C:\www\math\node_modules\is-retry-allowed\package.json
172 verbose read json C:\www\math\node_modules\is-stream\package.json
173 verbose read json C:\www\math\node_modules\is-symbol\package.json
174 verbose read json C:\www\math\node_modules\is-windows\package.json
175 verbose read json C:\www\math\node_modules\isarray\package.json
176 verbose read json C:\www\math\node_modules\isexe\package.json
177 verbose read json C:\www\math\node_modules\isobject\package.json
178 verbose read json C:\www\math\node_modules\js-tokens\package.json
179 verbose read json C:\www\math\node_modules\js-yaml\package.json
180 verbose read json C:\www\math\node_modules\json-schema-traverse\package.json
181 verbose read json C:\www\math\node_modules\json-stable-stringify-without-jsonify\package.json
182 verbose read json C:\www\math\node_modules\kind-of\package.json
183 verbose read json C:\www\math\node_modules\latest-version\package.json
184 verbose read json C:\www\math\node_modules\levn\package.json
185 verbose read json C:\www\math\node_modules\lodash\package.json
186 verbose read json C:\www\math\node_modules\lodash.debounce\package.json
187 verbose read json C:\www\math\node_modules\lowercase-keys\package.json
188 verbose read json C:\www\math\node_modules\lru-cache\package.json
189 verbose read json C:\www\math\node_modules\make-dir\package.json
190 verbose read json C:\www\math\node_modules\map-cache\package.json
191 verbose read json C:\www\math\node_modules\map-stream\package.json
192 verbose read json C:\www\math\node_modules\map-visit\package.json
193 verbose read json C:\www\math\node_modules\media-typer\package.json
194 verbose read json C:\www\math\node_modules\merge-descriptors\package.json
195 verbose read json C:\www\math\node_modules\method-override\package.json
196 verbose read json C:\www\math\node_modules\methods\package.json
197 verbose read json C:\www\math\node_modules\micromatch\package.json
198 verbose read json C:\www\math\node_modules\mime\package.json
199 verbose read json C:\www\math\node_modules\mime-db\package.json
200 verbose read json C:\www\math\node_modules\mime-types\package.json
201 verbose read json C:\www\math\node_modules\mimic-fn\package.json
202 verbose read json C:\www\math\node_modules\minimatch\package.json
203 verbose read json C:\www\math\node_modules\minimist\package.json
204 verbose read json C:\www\math\node_modules\mixin-deep\package.json
205 verbose read json C:\www\math\node_modules\mkdirp\package.json
206 verbose read json C:\www\math\node_modules\ms\package.json
207 verbose read json C:\www\math\node_modules\mute-stream\package.json
208 verbose read json C:\www\math\node_modules\nanomatch\package.json
209 verbose read json C:\www\math\node_modules\natural-compare\package.json
210 verbose read json C:\www\math\node_modules\negotiator\package.json
211 verbose read json C:\www\math\node_modules\nice-try\package.json
212 verbose read json C:\www\math\node_modules\nodemon\package.json
213 verbose read json C:\www\math\node_modules\nopt\package.json
214 verbose read json C:\www\math\node_modules\normalize-path\package.json
215 verbose read json C:\www\math\node_modules\npm-run-path\package.json
216 verbose read json C:\www\math\node_modules\object-assign\package.json
217 verbose read json C:\www\math\node_modules\object-copy\package.json
218 verbose read json C:\www\math\node_modules\object-keys\package.json
219 verbose read json C:\www\math\node_modules\object-visit\package.json
220 verbose read json C:\www\math\node_modules\object.pick\package.json
221 verbose read json C:\www\math\node_modules\on-finished\package.json
222 verbose read json C:\www\math\node_modules\once\package.json
223 verbose read json C:\www\math\node_modules\onetime\package.json
224 verbose read json C:\www\math\node_modules\optionator\package.json
225 verbose read json C:\www\math\node_modules\os-tmpdir\package.json
226 verbose read json C:\www\math\node_modules\p-finally\package.json
227 verbose read json C:\www\math\node_modules\package-json\package.json
228 verbose read json C:\www\math\node_modules\parseurl\package.json
229 verbose read json C:\www\math\node_modules\pascalcase\package.json
230 verbose read json C:\www\math\node_modules\path-dirname\package.json
231 verbose read json C:\www\math\node_modules\path-is-absolute\package.json
232 verbose read json C:\www\math\node_modules\path-is-inside\package.json
233 verbose read json C:\www\math\node_modules\path-key\package.json
234 verbose read json C:\www\math\node_modules\path-to-regexp\package.json
235 verbose read json C:\www\math\node_modules\pause-stream\package.json
236 verbose read json C:\www\math\node_modules\pify\package.json
237 verbose read json C:\www\math\node_modules\pinkie\package.json
238 verbose read json C:\www\math\node_modules\pinkie-promise\package.json
239 verbose read json C:\www\math\node_modules\pluralize\package.json
240 verbose read json C:\www\math\node_modules\posix-character-classes\package.json
241 verbose read json C:\www\math\node_modules\prelude-ls\package.json
242 verbose read json C:\www\math\node_modules\prepend-http\package.json
243 verbose read json C:\www\math\node_modules\process-nextick-args\package.json
244 verbose read json C:\www\math\node_modules\progress\package.json
245 verbose read json C:\www\math\node_modules\proxy-addr\package.json
246 verbose read json C:\www\math\node_modules\ps-tree\package.json
247 verbose read json C:\www\math\node_modules\pseudomap\package.json
248 verbose read json C:\www\math\node_modules\pstree.remy\package.json
249 verbose read json C:\www\math\node_modules\punycode\package.json
250 verbose read json C:\www\math\node_modules\qs\package.json
251 verbose read json C:\www\math\node_modules\range-parser\package.json
252 verbose read json C:\www\math\node_modules\raw-body\package.json
253 verbose read json C:\www\math\node_modules\rc\package.json
254 verbose read json C:\www\math\node_modules\readable-stream\package.json
255 verbose read json C:\www\math\node_modules\readdirp\package.json
256 verbose read json C:\www\math\node_modules\regex-not\package.json
257 verbose read json C:\www\math\node_modules\regexp.prototype.flags\package.json
258 verbose read json C:\www\math\node_modules\regexpp\package.json
259 verbose read json C:\www\math\node_modules\registry-auth-token\package.json
260 verbose read json C:\www\math\node_modules\registry-url\package.json
261 verbose read json C:\www\math\node_modules\remove-trailing-separator\package.json
262 verbose read json C:\www\math\node_modules\repeat-element\package.json
263 verbose read json C:\www\math\node_modules\repeat-string\package.json
264 verbose read json C:\www\math\node_modules\require-uncached\package.json
265 verbose read json C:\www\math\node_modules\resolve-from\package.json
266 verbose read json C:\www\math\node_modules\resolve-url\package.json
267 verbose read json C:\www\math\node_modules\restore-cursor\package.json
268 verbose read json C:\www\math\node_modules\ret\package.json
269 verbose read json C:\www\math\node_modules\rimraf\package.json
270 verbose read json C:\www\math\node_modules\rootpath\package.json
271 verbose read json C:\www\math\node_modules\run-async\package.json
272 verbose read json C:\www\math\node_modules\rxjs\package.json
273 verbose read json C:\www\math\node_modules\safe-buffer\package.json
274 verbose read json C:\www\math\node_modules\safe-regex\package.json
275 verbose read json C:\www\math\node_modules\semver\package.json
276 verbose read json C:\www\math\node_modules\semver-diff\package.json
277 verbose read json C:\www\math\node_modules\send\package.json
278 verbose read json C:\www\math\node_modules\serve-static\package.json
279 verbose read json C:\www\math\node_modules\set-immediate-shim\package.json
280 verbose read json C:\www\math\node_modules\set-value\package.json
281 verbose read json C:\www\math\node_modules\setprototypeof\package.json
282 verbose read json C:\www\math\node_modules\shebang-command\package.json
283 verbose read json C:\www\math\node_modules\shebang-regex\package.json
284 verbose read json C:\www\math\node_modules\signal-exit\package.json
285 verbose read json C:\www\math\node_modules\slice-ansi\package.json
286 verbose read json C:\www\math\node_modules\snapdragon\package.json
287 verbose read json C:\www\math\node_modules\snapdragon-node\package.json
288 verbose read json C:\www\math\node_modules\snapdragon-util\package.json
289 verbose read json C:\www\math\node_modules\source-map\package.json
290 verbose read json C:\www\math\node_modules\source-map-resolve\package.json
291 verbose read json C:\www\math\node_modules\source-map-url\package.json
292 verbose read json C:\www\math\node_modules\split\package.json
293 verbose read json C:\www\math\node_modules\split-string\package.json
294 verbose read json C:\www\math\node_modules\sprintf-js\package.json
295 verbose read json C:\www\math\node_modules\static-extend\package.json
296 verbose read json C:\www\math\node_modules\statuses\package.json
297 verbose read json C:\www\math\node_modules\stream-combiner\package.json
298 verbose read json C:\www\math\node_modules\string.prototype.matchall\package.json
299 verbose read json C:\www\math\node_modules\string_decoder\package.json
300 verbose read json C:\www\math\node_modules\strip-ansi\package.json
301 verbose read json C:\www\math\node_modules\strip-eof\package.json
302 verbose read json C:\www\math\node_modules\strip-json-comments\package.json
303 verbose read json C:\www\math\node_modules\supports-color\package.json
304 verbose read json C:\www\math\node_modules\symbol-observable\package.json
305 verbose read json C:\www\math\node_modules\table\package.json
306 verbose read json C:\www\math\node_modules\term-size\package.json
307 verbose read json C:\www\math\node_modules\text-table\package.json
308 verbose read json C:\www\math\node_modules\through\package.json
309 verbose read json C:\www\math\node_modules\timed-out\package.json
310 verbose read json C:\www\math\node_modules\tmp\package.json
311 verbose read json C:\www\math\node_modules\to-object-path\package.json
312 verbose read json C:\www\math\node_modules\to-regex\package.json
313 verbose read json C:\www\math\node_modules\to-regex-range\package.json
314 verbose read json C:\www\math\node_modules\touch\package.json
315 verbose read json C:\www\math\node_modules\type-check\package.json
316 verbose read json C:\www\math\node_modules\type-is\package.json
317 verbose read json C:\www\math\node_modules\undefsafe\package.json
318 verbose read json C:\www\math\node_modules\union-value\package.json
319 verbose read json C:\www\math\node_modules\unique-string\package.json
320 verbose read json C:\www\math\node_modules\unpipe\package.json
321 verbose read json C:\www\math\node_modules\unset-value\package.json
322 verbose read json C:\www\math\node_modules\unzip-response\package.json
323 verbose read json C:\www\math\node_modules\upath\package.json
324 verbose read json C:\www\math\node_modules\update-notifier\package.json
325 verbose read json C:\www\math\node_modules\uri-js\package.json
326 verbose read json C:\www\math\node_modules\urix\package.json
327 verbose read json C:\www\math\node_modules\url-parse-lax\package.json
328 verbose read json C:\www\math\node_modules\use\package.json
329 verbose read json C:\www\math\node_modules\util-deprecate\package.json
330 verbose read json C:\www\math\node_modules\utils-merge\package.json
331 verbose read json C:\www\math\node_modules\vary\package.json
332 verbose read json C:\www\math\node_modules\which\package.json
333 verbose read json C:\www\math\node_modules\widest-line\package.json
334 verbose read json C:\www\math\node_modules\wordwrap\package.json
335 verbose read json C:\www\math\node_modules\wrappy\package.json
336 verbose read json C:\www\math\node_modules\write\package.json
337 verbose read json C:\www\math\node_modules\write-file-atomic\package.json
338 verbose read json C:\www\math\node_modules\xdg-basedir\package.json
339 verbose read json C:\www\math\node_modules\yallist\package.json
340 warn package.json copy-descriptor@0.1.1 No README.md file found!
341 warn package.json estraverse@4.2.0 No README.md file found!
342 warn package.json get-value@2.0.6 No README.md file found!
343 warn package.json object-copy@0.1.0 No README.md file found!
344 warn package.json path-is-inside@1.0.2 No README.md file found!
345 warn package.json pstree.remy@1.1.0 No README.md file found!
346 warn package.json static-extend@0.1.2 No README.md file found!
347 verbose from cache C:\www\math\package.json
348 verbose readDependencies using package.json deps
349 verbose cache add [ 're2', null ]
350 silly cache add name=undefined spec="re2" args=["re2",null]
351 verbose parsed url Url {
351 verbose parsed url   protocol: null,
351 verbose parsed url   slashes: null,
351 verbose parsed url   auth: null,
351 verbose parsed url   host: null,
351 verbose parsed url   port: null,
351 verbose parsed url   hostname: null,
351 verbose parsed url   hash: null,
351 verbose parsed url   search: null,
351 verbose parsed url   query: null,
351 verbose parsed url   pathname: 're2',
351 verbose parsed url   path: 're2',
351 verbose parsed url   href: 're2' }
352 silly lockFile af2318e5-re2 re2
353 verbose lock re2 C:\Users\user\AppData\Roaming\npm-cache\af2318e5-re2.lock
354 silly lockFile af2318e5-re2 re2
355 verbose addNamed [ 're2', '' ]
356 verbose addNamed [ null, '' ]
357 silly lockFile 918d60b2-re2 re2@
358 verbose lock re2@ C:\Users\user\AppData\Roaming\npm-cache\918d60b2-re2.lock
359 silly addNameRange { name: 're2', range: '', hasData: false }
360 verbose url raw re2
361 verbose url resolving [ 'https://registry.npmjs.org/', './re2' ]
362 verbose url resolved https://registry.npmjs.org/re2
363 info retry registry request attempt 1 at 23:51:20
364 http GET https://registry.npmjs.org/re2
365 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
366 info retry registry request attempt 2 at 23:51:30
367 http GET https://registry.npmjs.org/re2
368 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
369 info retry registry request attempt 3 at 23:52:30
370 http GET https://registry.npmjs.org/re2
371 silly lockFile 918d60b2-re2 re2@
372 error Error: unable to get local issuer certificate
372 error     at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
372 error     at emitNone (events.js:106:13)
372 error     at TLSSocket.emit (events.js:208:7)
372 error     at TLSSocket._finishInit (_tls_wrap.js:639:8)
372 error     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)
373 error If you need help, you may report this log at:
373 error     <http://github.com/isaacs/npm/issues>
373 error or email it to:
373 error     <npm-@googlegroups.com>
374 error System Windows_NT 6.1.7601
375 error command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "re2"
376 error cwd C:\www\math
377 error node -v v8.11.3
378 error npm -v 1.1.48
379 error code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
380 verbose exit [ 1, true ]
`
```

**Comment by uhop** [comment]
Lines like that:

```txt
370 http GET https://registry.npmjs.org/re2
371 silly lockFile 918d60b2-re2 re2@
372 error Error: unable to get local issuer certificate
[...]
379 error code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
```

Point to problems with an HTTPS (?) certificate of https://registry.npmjs.org/re2 and could indicate multiple problems, none of them with `re2` code &mdash; from problems with `npm` servers to problems with your local network. They can be transient or permanent. I suggest opening a bug against `npm` so they can trace the problem.
