### ISSUE TITLE
Can't install on Freebsd 10.03-RELEASE-p3

### ISSUE THREAD

**Issue by Kamil93** [uhop/node-re2#5]
```
[someuser@s6]:<~>$ npm install re2
> re2@1.3.3 install /usr/home/someuser/node_modules/re2
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gmake: Wejście do katalogu '/usr/home/someuser/node_modules/re2/build'
  CXX(target) Release/obj.target/re2/lib/addon.o
In file included from ../lib/addon.cc:1:
In file included from ../lib/./wrapped_re2.h:6:
In file included from ../../nan/nan.h:1737:
../../nan/nan_string_bytes.h:268:14: warning: unused variable 'written' [-Wunused-variable]
      size_t written = base64_encode(buf, buflen, dst, dlen);
             ^
../../nan/nan_string_bytes.h:285:14: warning: unused variable 'written' [-Wunused-variable]
      size_t written = hex_encode(buf, buflen, dst, dlen);
             ^
../lib/addon.cc:73:18: error: cannot initialize a member subobject of type 'void (*)(v8::Handle<v8::Object>)' with an lvalue of type
      'void (Handle<v8::Object>, Handle<v8::Object>)': different number of parameters (1 vs 2)
NODE_MODULE(re2, Initialize)
                 ^~~~~~~~~~
/home/someuser/.node-gyp/0.8.25/src/node.h:235:7: note: expanded from macro 'NODE_MODULE'
      regfunc,                                                        \
      ^
In file included from ../lib/addon.cc:1:
In file included from ../lib/./wrapped_re2.h:5:
In file included from /home/someuser/.node-gyp/0.8.25/src/node.h:62:
/home/someuser/.node-gyp/0.8.25/deps/v8/include/v8.h:202:5: error: assigning to 'v8::Object *volatile' from incompatible type
      'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/home/someuser/.node-gyp/0.8.25/deps/v8/include/v8.h:145:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../lib/addon.cc:24:32: note: in instantiation of function template specialization 'v8::Handle<v8::Object>::Handle<v8::Value>' requested
      here
                char* s = node::Buffer::Data(info[0]);
                                             ^
2 warnings and 2 errors generated.
gmake: *** [re2.target.mk:131: Release/obj.target/re2/lib/addon.o] Błąd 1
gmake: Opuszczenie katalogu '/usr/home/someuser/node_modules/re2/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/home/someuser/.nvm/v0.8.25/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:2       3)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:686:10)
gyp ERR! System FreeBSD 10.3-RELEASE-p3
gyp ERR! command "node" "/usr/home/someuser/.nvm/v0.8.25/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/someuser/node_modules/re2
gyp ERR! node -v v0.8.25
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok
/usr/home/someuser

```

**Comment by uhop** [comment]
It looks like you use node 0.8, which is not supported &mdash; given that the current version is 6 (six), and we are about to move to 7. Versions 0.10 to 5 are tested routinely: https://github.com/uhop/node-re2/blob/master/.travis.yml and I use 6 on my workstations daily.

In general, 0.8 was supported before &mdash; please try previous versions of `re2`. But we are limited by [nan](https://github.com/nodejs/nan) &mdash; if it doesn't support a certain version of node, we cannot support it either. Not without forking the repo.

I suggest to switch to a newer version of node. Personally I found [nvm](https://github.com/creationix/nvm) to be the best tool to manage versions of node.

**Comment by Kamil93** [comment]
With node v4.4.7:

```
module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /usr/local/lib/compat/libstdc++.so.6: version GLIBCXX_3.4.10 required by /usr/home/someuser/node_modules/re2/build/Release/re2.node not found
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/home/someuser/node_modules/re2/re2.js:3:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

Just by requiring module:
`
var RE2 = require("re2");`
