### ISSUE TITLE
Module did not self-register while using Worker Threads

### ISSUE THREAD

**Issue by BannerBomb** [uhop/node-re2#57]
When trying to use the package in a project that uses Worker Threads causes this error, but if I change to use Child Processes it works perfectly fine.
```prolog
events.js:170
      throw er; // Unhandled 'error' event
      ^
Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:857:18)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/bannerbomb/Desktop/Github_Stuff/Discord_Bots/Highlight (copy)/branches/master/node_modules/re2/re2.js:3:11)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
Emitted 'error' event at:
    at Worker.[kOnErrorMessage] (internal/worker.js:170:10)
    at Worker.[kOnMessage] (internal/worker.js:180:37)
    at MessagePort.Worker.(anonymous function).on (internal/worker.js:113:57)
    at MessagePort.emit (events.js:193:13)
    at MessagePort.onmessage (internal/worker/io.js:73:8)
```

I am using npm version `6.12.0`
and node version `11.15.0` also tried with `13.7.0`

**Comment by uhop** [comment]
Worker Threads is a relatively new feature of Node. I used Child Processes before but never Worker Threads &mdash; unfortunately, I have no experience with them and how to load modules into them. I was kind of expecting that we can use unmodified modules. If you can find relevant documentation on how to structure modules so they can be used with Worker Threads and it doesn't break their normal use or point out what is wrong with my code I would appreciate it.

As always patches are welcome!

**Comment by uhop** [comment]
@BannerBomb Could you share a minimal repro case with me? Thank you in advance.

**Comment by uhop** [comment]
I modified the way the module is initialized. You can test your code using the `master` branch.

I didn't publish the change yet because it broke Node 8. I will investigate it but it is likely that the new way of initialization is not supported on that version. Given that Node 8 is EOL since 12/31/2019, I will likely drop it in the next release.

**Comment by BannerBomb** [comment]
Sorry I didn't see that you messaged back till now, I'll try to make a reproduction when I can get back on my computer. It occured when I sharded my discord.js bot and enabled worker threads as the sharding method. I use RE2 but when it went to read the require('re2') in my file it while booting it caused this error.

**Comment by BannerBomb** [comment]
By the way I use Nodejs 13, and discord.js v12.

**Comment by uhop** [comment]
Added in https://github.com/uhop/node-re2/commits/1.11.0

**Comment by niftylettuce** [comment]
This is great, because it will work in [Bree](https://jobscheduler.net) now too, thanks @uhop !
