### ISSUE TITLE
Does not seem to install on win7

### ISSUE THREAD

**Issue by inf3rno** [uhop/node-re2#60]
```
inf3rno@inf3rno-PC MINGW64 ~/Desktop/Új mappa
$ npm install re2 --save

> re2@1.10.5 install C:\Users\inf3rno\Desktop\Új mappa\node_modules\re2
> node-gyp rebuild


C:\Users\inf3rno\Desktop\▒j mappa\node_modules\re2>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Traceback (most recent call last):
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 547, in main
    return gyp_main(args)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 532, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2012, in GenerateOutput
    msvs_version)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1847, in _CreateProjectObjects
    guid = _GetGuidOfProject(proj_path, spec)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 914, in _GetGuidOfProject
    guid = guid or MSVSNew.MakeGuid(proj_path)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSNew.py", line 48, in MakeGuid
    d = hashlib.md5((str(seed) + str(name)).encode('utf-8')).hexdigest().upper()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xda in position 33: ordinal not in range(128)
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\inf3rno\Desktop\Új mappa\node_modules\re2
gyp ERR! node -v v13.8.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\inf3rno\Desktop\Új mappa\package.json'
npm WARN Új mappa No description
npm WARN Új mappa No repository field.
npm WARN Új mappa No README data
npm WARN Új mappa No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! re2@1.10.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the re2@1.10.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\inf3rno\AppData\Roaming\npm-cache\_logs\2020-03-19T13_32_24_702Z-debug.log

```

**Comment by inf3rno** [comment]
I suspect that it does not like Hungarian directory names. I'll try out with a different name...

**Comment by inf3rno** [comment]
Yes, it was the directory name. You could add this to the docs if not included already.

```
inf3rno@inf3rno-PC MINGW64 ~/Desktop/mappa
$ npm install re2 --save

> re2@1.10.5 install C:\Users\inf3rno\Desktop\mappa\node_modules\re2
> node-gyp rebuild


C:\Users\inf3rno\Desktop\mappa\node_modules\re2>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  addon.cc
  new.cc
  exec.cc
  test.cc
  match.cc
  replace.cc
  search.cc
  split.cc
..\lib\replace.cc(251): warning C4018: '>': signed/unsigned mismatch [C:\Users\inf3rno\Desktop\mappa\node_modules\re2\build\re2.vcxproj]
..\lib\replace.cc(399): warning C4018: '>': signed/unsigned mismatch [C:\Users\inf3rno\Desktop\mappa\node_modules\re2\build\re2.vcxproj]
  to_string.cc
  accessors.cc
  util.cc
  bitstate.cc
  compile.cc
  dfa.cc
  filtered_re2.cc
  mimics_pcre.cc
  nfa.cc
  onepass.cc
  parse.cc
  perl_groups.cc
  prefilter.cc
  prefilter_tree.cc
  prog.cc
  re2.cc
  regexp.cc
  set.cc
  simplify.cc
  stringpiece.cc
  tostring.cc
  unicode_casefold.cc
  unicode_groups.cc
  pcre.cc
  rune.cc
  strutil.cc
  win_delay_load_hook.cc
     Creating library C:\Users\inf3rno\Desktop\mappa\node_modules\re2\build\Release\re2.lib and object C:\Users\inf3rno\Desktop\mappa\node_modules\re2\build\Release\re2.exp
  re2.vcxproj -> C:\Users\inf3rno\Desktop\mappa\node_modules\re2\build\Release\\re2.node
  re2.vcxproj -> C:\Users\inf3rno\Desktop\mappa\node_modules\re2\build\Release\re2.pdb (Full PDB)
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\inf3rno\Desktop\mappa\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\inf3rno\Desktop\mappa\package.json'
npm WARN mappa No description
npm WARN mappa No repository field.
npm WARN mappa No README data
npm WARN mappa No license field.

+ re2@1.10.5
added 1 package from 1 contributor and audited 40 packages in 13.514s
found 0 vulnerabilities

```

**Comment by uhop** [comment]
I will add it to docs, thx.

**Comment by uhop** [comment]
Done.
