### ISSUE TITLE
Python `SyntaxError: invalid syntax` while trying to install

### ISSUE THREAD

**Issue by kvz** [uhop/node-re2#61]
Here's what I got:

```bash
error /srv/current/api2/node_modules/re2: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /srv/current/api2/node_modules/re2
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.15.1 | linux | x64
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /home/ubuntu/.nix-profile/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:281:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Linux 4.15.0-1063-aws
```

My Python version:

```bash
$ /home/ubuntu/.nix-profile/bin/python --version
Python 3.7.0
```

Any idea how I could resolve this?

**Comment by kvz** [comment]
I guess this is not a re2 issue, but something with gyp only supporting python 2.7 https://github.com/nodejs/node-gyp/issues/324

**Comment by uhop** [comment]
Added to the docs.

**Comment by kvz** [comment]
FWIW upgrading gyp did not work, what did work for us was installing python 2.7 and passing: 

    PYTHON=<location to python27> npm

**Comment by uhop** [comment]
Updated the docs with this information. Thank you!
